title: StationCast
description: Personal weather station app for iPhone
baseurl: ""
url: https://stationcast.app

markdown: kramdown
permalink: /:title

plugins:
  - jekyll-feed

include:
  - .well-known

exclude:
  - .gitignore
  - README.md
